\c kidscore2 kids
\i sql/t_temp.sql
\i sql/m_accessipaddress.sql
\i sql/m_adminfunction.sql
\i sql/m_attribute.sql
\i sql/m_attributerelation.sql
\i sql/m_authoritygroup.sql
\i sql/m_businesscode.sql
\i sql/m_category.sql
\i sql/m_categoryrelation.sql
\i sql/m_certificateclass.sql
\i sql/m_charactar.sql
\i sql/m_closedday.sql
\i sql/m_commonfunction.sql
\i sql/m_company.sql
\i sql/m_companynamelink.sql
\i sql/m_companyprintname.sql
\i sql/m_conversionclass.sql
\i sql/m_copyright.sql
\i sql/m_country.sql
\i sql/m_deliverymethod.sql
\i sql/m_demand.sql
\i sql/m_estimate.sql
\i sql/m_estimatedefault.sql
\i sql/m_estimatestandardrate.sql
\i sql/m_estimatestatus.sql
\i sql/m_function.sql
\i sql/m_functionauthority.sql
\i sql/m_goodsplanprogress.sql
\i sql/m_group.sql
\i sql/m_grouprelation.sql
\i sql/m_imagerelation.sql
\i sql/m_invoice.sql
\i sql/m_mailform.sql
\i sql/m_message.sql
\i sql/m_mold.sql
\i sql/m_moldreport.sql
\i sql/m_monetaryrate.sql
\i sql/m_monetaryrateclass.sql
\i sql/m_monetaryunit.sql
\i sql/m_order.sql
\i sql/m_orderstatus.sql
\i sql/m_organization.sql
\i sql/m_paycondition.sql
\i sql/m_product.sql
\i sql/m_productform.sql
\i sql/m_productprice.sql
\i sql/m_productstatus.sql
\i sql/m_productunit.sql
\i sql/m_pulldown.sql
\i sql/m_purchaseorder.sql
\i sql/m_receive.sql
\i sql/m_receivestatus.sql
\i sql/m_reportclass.sql
\i sql/m_sales.sql
\i sql/m_salesclass.sql
\i sql/m_salesclassdivisonlink.sql
\i sql/m_salesdivision.sql
\i sql/m_salesstatus.sql
\i sql/m_slip.sql
\i sql/m_slipkind.sql
\i sql/m_slipkindrelation.sql
\i sql/m_stock.sql
\i sql/m_stockclass.sql
\i sql/m_stockitem.sql
\i sql/m_stockstatus.sql
\i sql/m_stocksubject.sql
\i sql/m_systeminformation.sql
\i sql/m_targetage.sql
\i sql/m_tax.sql
\i sql/m_taxclass.sql
\i sql/m_user.sql
\i sql/seq_businesscodeid.sql
\i sql/seq_cacheid.sql
\i sql/seq_moldreportrelationid.sql
\i sql/t_cache.sql
\i sql/t_estimatedetail.sql
\i sql/t_exclusivecontrol.sql
\i sql/t_exportdata.sql
\i sql/t_goodsplan.sql
\i sql/t_image.sql
\i sql/t_invoicedetail.sql
\i sql/t_loginsession.sql
\i sql/t_moldhistory.sql
\i sql/t_moldreportdetail.sql
\i sql/t_moldreportrelation.sql
\i sql/t_orderdetail.sql
\i sql/t_processinformation.sql
\i sql/t_product.sql
\i sql/t_purchaseorderdetail.sql
\i sql/t_receivedetail.sql
\i sql/t_report.sql
\i sql/t_salesdetail.sql
\i sql/t_sequence.sql
\i sql/t_slipdetail.sql
\i sql/t_stockdetail.sql
